name: Build .NET MAUI App For Android
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Keystore File
      run: |
        echo "${{ secrets.Android_Keyfile }}" > myapp.keystore.asc
        gpg -d --passphrase "123456" --batch myapp.keystore.asc > myapp.keystore
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build JboxWebdav.MauiApp/JboxWebdav.MauiApp.csproj -c Release -f net6.0-android /p:AndroidSigningKeyStore=myapp.keystore /p:AndroidSigningKeyAlias=key /p:AndroidSigningKeyPass="123456" /p:AndroidSigningStorePass="123456" --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
